version: 2

jobs:
  build:
    docker:
    - image: streakphp/php72-cli:latest
      environment:
      - COMPOSER_NO_INTERACTION=1
      - COMPOSER_ALLOW_SUPERUSER=1
    working_directory: ~/streak-bundle
    steps:
      - checkout

      - run: composer self-update
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.json" }}
            - composer-v1-
      - run: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.json" }}
          paths:
            - vendor/

      - run: bin/php-cs-fixer fix --config=.php_cs.dist --diff --diff-format=udiff -v --show-progress=estimating --dry-run
      - run: php -d zend_extension=xdebug.so bin/phpunit

      - store_artifacts:
          path: build/code-coverage/
          destination: code-coverage/
      - store_test_results:
          path: build/

      - run: bash <(curl -s https://codecov.io/bash) -Z
