version: '3'
services:

  php:
    image: streakphp/php74-cli:latest
    volumes:
      - .:/var/www/project
      - ./docker/php/etc/php/7.4/cli/php.ini:/etc/php/7.4/cli/php.ini
    working_dir: /var/www/project
    environment:
      COMPOSER_ALLOW_SUPERUSER: 1
      COMPOSER_NO_INTERACTION: 1
      COMPOSER_CACHE_DIR: /var/www/project/build/.composer
      XDEBUG_MODE: 'develop,debug,coverage'
