services:
  streak.aggregate_root.command_handlers:
    class: Streak\Application\CommandHandler\AggregateRootHandler
    arguments:
      - '@Streak\Domain\AggregateRoot\Repository'
    tags:
      - 'streak.command_handler'
