services:
  streak.event_listener.query_handler:
    class: Streak\Application\QueryHandler\EventListenerHandler
    arguments:
      - '@Streak\Domain\Event\Subscription\Repository'
    tags:
      - 'streak.query_handler'

